### PR TITLE
Bg remove unwanted fs 166152678

### PR DESCRIPTION
**Pull request by benshidanny11**
#### What does this PR do?
- It modifies the codes to be well structured
#### Description of Task to be completed?
- Remove .nyc_output form git
- To write a proper README.md file
- To move all babel and chai packages from dependencies to dev dependencies
- To add dotenv to gitignore
- To setup babel in a proper way
- To remove all comments codes.
- Remove all eslint disable from your code
- Test for other things apart from status code
- Abstract all dummy data in your file to another file
#### How should this be manually tested?
**On github**
- https://github.com/benshidanny11/QuickCredit
#### What are the relevant pivotal tracker stories?
- #166152678

### CODE REVIEW

**Comment by Kenec** [comment]
Please resolve the conflict in this PR first.

**Comment by Kenec** [comment]
PR should have minimal file changes. 96 files changes are way too much for PR.

**Comment by Kenec** [comment]
Also, PR should contain just one commit. Unless you are merging to master. But from branch to develop, the ideal should be one commit.

**Comment by Kenec** [comment]
`.env` file contains your application secrets and should not be pushed to the Github repository.

**Comment by benshidanny11** [comment]
> `.env` file contains your application secrets and should not be pushed to the Github repository.

I added it to gitignore I don't know why it is not ignored!

**Comment by Kenec** [comment]
Please remove these folders from this PR: .nyc_output, bin, build, and coverage

**Pull request closed without merging**
